# Generated by Django 5.1 on 2024-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokter_spesialis', models.CharField(max_length=50)),
                ('nama_dokter', models.CharField(max_length=50)),
                ('jadwal_praktek', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mr', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.TextField()),
            ],
        ),
    ]
