# Generated by Django 5.1 on 2024-08-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_antrian', models.IntegerField()),
                ('waktu_update', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasien.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien')),
            ],
        ),
    ]
