# Generated by Django 5.1 on 2024-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='tanggal_berobat',
            field=models.DateField(default='2024-08-25'),
            preserve_default=False,
        ),
    ]
